In [1]:
import numpy as np

In [27]:
def normalize(M):
    """
    Subfunction for T. It normalizes the matrix given as input.
    
    INPUT:
        - M = A matrix M.
        
    OUTPUT:
        - M0 = The matrix M normalized, with rows that add to 1.     
    """
    
    M0=np.array(M)
    if M0.ndim == 1:
        s= M0.sum()
        return np.divide(M0,s)
        
    elif M0.ndim == 2:
        s=M0.sum(axis=1)
        return np.divide(M0,s[:,np.newaxis])
    else:
        return "Normalize. Wrong input"

In [55]:
def stationary_sol(T):
    """
    Given a random matrix T, returns a stationary sol a, s.t. aT=a
    
    INPUT:
        - T = Some square matrix.
        
    OUTPUT:
        - the stationary vector of the matrix.   
    """
    
    T0=normalize(T)
    eig=np.linalg.eig(T0)
    for i in range(len(eig[0])):
        if np.around(eig[0][i])==1: #considers only integer part
            return np.real(eig[1][i])
    return "No eigenvalue 1"

In [ ]:
def has_stationary(T):
    """
    Checks whether a transition matrix from a markov process has a unique stationary solution.
    It will be checked: 
        1. Is it a stochastic matrix?
        2. Is it irreducible?
        3. 
    
    INPUT:
        - T = Some square matrix.
        
    OUTPUT:
        - 
    """
    
    

In [52]:
def stationary_sol(T):
    """
    Given a random matrix T, returns a stationary sol a, s.t. aT=a
    
    INPUT:
        - T = Some square matrix.
        
    OUTPUT:
        - the stationary vector of the matrix.   
    """
    
    #if has_stationary(T):
    T0=normalize(T)
    eig=np.linalg.eig(T0)
    for i in range(len(eig[0])):
        if np.around(eig[0][i])==1: #considers only integer part
            return np.real(eig[1][i])
    return "No eigenvalue 1"
    #else:
        #return "No stationary solution"

In [32]:
C=np.array([[ 0, 1, 0],[0,1,1],[ 1, 0,0]])
normalize(C)

array([[ 0. ,  1. ,  0. ],
       [ 0. ,  0.5,  0.5],
       [ 1. ,  0. ,  0. ]])

In [53]:
stationary_sol(C)

[[ 0.   1.   0. ]
 [ 0.   0.5  0.5]
 [ 1.   0.   0. ]]
(array([-0.25+0.66143783j, -0.25-0.66143783j,  1.00+0.j        ]), array([[-0.18898224+0.5j , -0.18898224-0.5j , -0.57735027+0.j  ],
       [-0.28347335-0.25j, -0.28347335+0.25j, -0.57735027+0.j  ],
       [ 0.75592895+0.j  ,  0.75592895-0.j  , -0.57735027+0.j  ]]))
(-0.25+0.661437827766j)
(-0.25-0.661437827766j)
(1+0j)


array([ 0.75592895+0.j,  0.75592895-0.j, -0.57735027+0.j])