In [2]:
import numpy as np

In [3]:
def Visit(u,Visited,L,M):
    """
    Recursive subfunction for kosarajus
    
    INPUT:
        
        - u = An integer, which represents a vertex (in our numeration).
        - Visited = A list of the vertices already visited.
        - L = an ordered list of graph vertices, that will grow to contain each vertex once.
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
        
        - It just adds in order vertices to the list L.
    
    """
    out=M[u,:]
    if not(u in Visited):
        Visited.append(u)
        for i in range(len(out)):
            if not(out[i]==0):
                Visit(i,Visited,L,M)
        L.insert(0,u) 
    return

In [4]:
def Assign(u,root,components,M):
    """
    Recursive subfunction for kosarajus
    Strong components are to be represented by appointing a separate root vertex for each component,
    and assigning to each vertex the root vertex of its component.
    
    INPUT:
        
        - u = An integer, which represents a vertex (in our numeration) that has to be
        assigned to some component.
        - root = An integer, which represents a component.
        - components = A dictionary containing the vertices (numerated from 0 to n-1), 
        each vertex associated to the root representing its component.
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
    
        - It just changes the dictionary components, assigning to each vertex its root.
    
    """
    
    in_=[i for i in M[:,u]]
    
    if not u in components:
        components[u]=root
        for i in range(len(in_)):
            if not(in_[i]==0):
                Assign(i,root,components,M)
    return
    

In [5]:
def Assign2(u,root,LIST,components,M):
    """
    Recursive subfunction for kosarajus
    Strong components are to be represented by appointing a separate root vertex for each component,
    and assigning to each vertex the root vertex of its component.
    
    INPUT:
        
        - u = An integer, which represents a vertex (in our numeration) that has to be
        assigned to some component.
        - root = An integer, which represents a component.
        
        - LIST = A list of vertices that are not yet introduced in the dictionary.
        
        - components = A dictionary containing the vertices (numerated from 0 to n-1), 
        each vertex associated to the root representing its component.
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
    
        - It just changes the dictionary components, assigning to each vertex its root.
    
    """
    
    in_=[i for i in M[:,u]]
    
    if u in LIST:
        
        if not root in components:
            components[root]=[u]
        elif root in components:
            components[root].append(u)
        LIST.remove(u)
            
        for i in range(len(in_)):
            if not(in_[i]==0):
                Assign2(i,root,LIST,components,M)
    return

In [6]:
def kosarajus_alg(M):
    """
    Returns a dictionary containing the vertices and their inclusion in strong components.
    Strong components are to be represented by appointing a separate root vertex for each component,
    and assigning to each vertex the root vertex of its component.
    If the graph is represented as an adjacency matrix, the algorithm requires Ο(V^2) time.
    
    INPUT:
    
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
    
        - components = A dictionary containing the vertices (numerated from 0 to n-1), 
        each vertex associated to the root representing its component.
    
    """
    
    Visited=[]
    L=[]
    
    components={}
    
    Vertices= [i for i in range(len(M[:,1]))]
    
    for i in Vertices:
        Visit(i,Visited,L,M)
    for u in L:
        Assign(u,u,components,M)
    return components        

In [7]:
def kosarajus_algo2(M):
    """
    Returns a dictionary containing the vertices and their inclusion in strong components.
    Strong components are to be represented by appointing a separate root vertex for each component,
    and assigning to each root the list of vertices inside that component.
    If the graph is represented as an adjacency matrix, the algorithm requires Ο(V^2) time.
    
    INPUT:
    
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
    
        - components = A dictionary containing the components (numerated from 0 to ..), 
        each root associated to a list of vertices that are part of that component.
    
    """
    
    Visited=[]
    L=[]
    
    components={}
    
    Vertices= [i for i in range(len(M[:,1]))]
    LIST=list(Vertices)
    
    for i in Vertices:
        Visit(i,Visited,L,M)
    for u in L:
        Assign2(u,u,LIST,components,M)
    return components      

In [31]:
def obtain_active_set(T):
    """
    Function for other parts of the project. It gets the biggest connected component of the matrix 
    that we are given.
    
    INPUT:
        - T = The probability transition matrix of the markov model.
    
    OUTPUT:
        - C = A square matrix. The biggest connected component of the matrix.
        - L = A list of vertices. The states of T that correspond to the biggest component.
    
    """
    
    b=0
    j=0
    components=kosarajus_algo2(T)
    for i in components:
        a=len(components[i])
        if a>b:
            b=a
            j=i
    L=list(components[j])
    C=np.array([T[i,:] for i in L])
    C=np.array([C[:,i] for i in L])
    return (C,L)

In [32]:
M1=np.array([[0.5,0.5],[0.1,0.9]])
M1

array([[ 0.5,  0.5],
       [ 0.1,  0.9]])

In [34]:
a=np.array([[0,1,0,0,0,0,0],[0,1/2,1/2,0,0,0,0],[1/2,0,1/2,0,0,0,0],[0,0,1/4,1/2,1/4,0,0],[0,0,0,0,0,1/2,1/2]
            ,[0,0,0,1,0,0,0],[0,0,0,0,0,0,1]])
kosarajus_algo2(a)

{0: [0, 2, 1], 3: [3, 5, 4], 6: [6]}

In [30]:
M2=np.random.rand(10,10)
M2

array([[ 0.77342924,  0.88123755,  0.93391871,  0.41147898,  0.01942876,
         0.21232949,  0.61094649,  0.04292789,  0.69906564,  0.29857063],
       [ 0.05963261,  0.84038975,  0.51772488,  0.58329488,  0.84052009,
         0.20255397,  0.6454204 ,  0.81054557,  0.55281882,  0.04448282],
       [ 0.30182656,  0.51788511,  0.57048955,  0.11358506,  0.46228348,
         0.60231886,  0.78081028,  0.90069549,  0.50255913,  0.04882871],
       [ 0.95339107,  0.69679291,  0.09069482,  0.91848151,  0.6206522 ,
         0.3239811 ,  0.14005584,  0.78736777,  0.88791862,  0.64592273],
       [ 0.89253824,  0.33239988,  0.53409622,  0.07916055,  0.09372219,
         0.26136489,  0.94901861,  0.27098832,  0.8053857 ,  0.4852336 ],
       [ 0.28613619,  0.4528511 ,  0.78206502,  0.18443035,  0.04652935,
         0.21262223,  0.90433656,  0.06847831,  0.45631058,  0.28315825],
       [ 0.63108847,  0.69797056,  0.40886189,  0.42141288,  0.82058935,
         0.7759894 ,  0.63925523,  0.8859665 

In [11]:
print(kosarajus_alg(M2))
components=kosarajus_algo2(M2)
print(components)
for i in components:
    print(i)

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}
{0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]}
0


In [12]:
M3=np.array([[0.5,0.5,0,0],[0.1,0.9,0,0],[0,0,1,0],[0,0,0,1]])
print(M3)
components=kosarajus_algo2(M3)
print(components)
for i in components:
    print(i)
    print(components[i])

[[ 0.5  0.5  0.   0. ]
 [ 0.1  0.9  0.   0. ]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]
{0: [0, 1], 2: [2], 3: [3]}
0
[0, 1]
2
[2]
3
[3]


In [13]:
obtain_active_set(M3)

(array([[ 0.5,  0.1],
        [ 0.5,  0.9]]), [0, 1])

In [14]:
M3[0,:]

array([ 0.5,  0.5,  0. ,  0. ])

In [15]:
M3[1,:]

array([ 0.1,  0.9,  0. ,  0. ])

In [16]:
c=np.array([M3[0,:],M3[1,:]])
c=np.array([c[:,0],c[:,1]])
c

array([[ 0.5,  0.1],
       [ 0.5,  0.9]])

In [17]:
print(kosarajus_alg(M3))
kosarajus_algo2(M3)

{0: 0, 1: 0, 2: 2, 3: 3}


{0: [0, 1], 2: [2], 3: [3]}

In [29]:
D=np.array([[0,0,0,0,0,0,1,0,0,0],[0,0.3,0.3,0.1,0.3,0,0,0,0,0],[0,0,0.6,0,0,0,0,0.4,0,0],[0,0,0,1,0,0,0,0,0,0],
            [0,0.4,0,0,0,0.3,0,0.3,0,0],[0,0,0,0.9,0,0,0.1,0,0,0],[0,0,0,0,0,0,0,0,0,1],[0,0.8,0,0,0,0,0,0.2,0,0],
           [0,0,0,0,0,0,0,0,1,0],[1,0,0,0,0,0,0,0,0,0]])
kosarajus_algo2(D)

{0: [0, 9, 6], 1: [1, 4, 7, 2], 3: [3], 5: [5], 8: [8]}

In [22]:
d=obtain_active_set(D)[0]
d

array([[ 0.3,  0.4,  0.8,  0. ],
       [ 0.3,  0. ,  0. ,  0. ],
       [ 0. ,  0.3,  0.2,  0.4],
       [ 0.3,  0. ,  0. ,  0.6]])

In [27]:
stationary_sol(d)

array([ 0.25,  0.25,  0.25,  0.25])