In [ ]:
import numpy as np

In [81]:
def Visit(u,Visited,L,M):
    """
    Recursive subfunction for kosarajus
    
    INPUT:
        
        - u = An integer, which represents a vertex (in our numeration).
        - Visited = A list of the vertices already visited.
        - L = an ordered list of graph vertices, that will grow to contain each vertex once.
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
        
        - It just adds in order vertices to the list L.
    
    """
    out=M[u,:]
    if not(u in Visited):
        Visited.append(u)
        for i in range(len(out)):
            if not(out[i]==0):
                Visit(i,Visited,L,M)
        L.insert(0,u) 
    return

In [100]:
def Assign(u,root,components,M):
    """
    Recursive subfunction for kosarajus
    Strong components are to be represented by appointing a separate root vertex for each component,
    and assigning to each vertex the root vertex of its component.
    
    INPUT:
        
        - u = An integer, which represents a vertex (in our numeration) that has to be
        assigned to some component.
        - root = An integer, which represents a component.
        - components = A dictionary containing the vertices (numerated from 0 to n-1), 
        each vertex associated to the root representing its component.
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
    
        - It just changes the dictionary components, assigning to each vertex its root.
    
    """
    
    in_=[i for i in M[:,u]]
    
    if not u in components:
        components[u]=root
        for i in range(len(in_)):
            if not(in_[i]==0):
                Assign(i,root,components,M)
    return
    

In [114]:
def kosarajus_alg(M):
    """
    Returns a dictionary containing the vertices and their inclusion in strong components.
    Strong components are to be represented by appointing a separate root vertex for each component,
    and assigning to each vertex the root vertex of its component.
    
    INPUT:
    
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
    
        - components = A dictionary containing the vertices (numerated from 0 to n-1), 
        each vertex associated to the root representing its component.
    
    """
    
    Visited=[]
    L=[]
    
    components={}
    
    Vertices= [i for i in range(len(M[:,1]))]
    
    for i in Vertices:
        Visit(i,Visited,L,M)
    for u in L:
        Assign(u,u,components,M)
    return components        

In [115]:
M1=np.array([[0.5,0.5],[0.1,0.9]])
M1

array([[ 0.5,  0.5],
       [ 0.1,  0.9]])

In [116]:
kosarajus_alg(M1)

{0: 0, 1: 0}

In [119]:
M2=np.random.rand(5,5)
M2

array([[ 0.4240848 ,  0.49146777,  0.79290605,  0.23991104,  0.84977666],
       [ 0.54248827,  0.43515223,  0.57269574,  0.02042673,  0.52364522],
       [ 0.70838939,  0.91987347,  0.53969374,  0.59643248,  0.12555927],
       [ 0.57787202,  0.03001013,  0.93418285,  0.03391739,  0.43406192],
       [ 0.99136258,  0.53707816,  0.72837864,  0.59796389,  0.31360441]])

In [120]:
kosarajus_alg(M2)

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0}

In [124]:
M3=np.array([[0.5,0.5,0,0],[0.1,0.9,0,0],[0,0,1,0],[0,0,0,1]])
M3

array([[ 0.5,  0.5,  0. ,  0. ],
       [ 0.1,  0.9,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [125]:
kosarajus_alg(M3)

{0: 0, 1: 0, 2: 2, 3: 3}