In [42]:
# coding: utf-8

# Look Python PEP for information about how to properly (and beautifully) code in Python.
# Look at google: numpy + "term" (svd for example) for information about numpy functions.

# Numpy array:
# np.array([[0,1,2,3],[4,5,6,7]]) creates a matrix 2x4.

# In[ ]:

import numpy as np
import operator as op


# In[ ]:

M1=np.array([[0.5,0.5],[0.1,0.9]])
M1

array([[ 0.5,  0.5],
       [ 0.1,  0.9]])

In [3]:
M1[:,1]

array([ 0.5,  0.9])

In [4]:
M2=np.random.rand(3,3)
M2

array([[ 0.71353678,  0.81560565,  0.59779976],
       [ 0.21322577,  0.02264318,  0.95387865],
       [ 0.02565694,  0.51688337,  0.30994962]])

In [5]:
M3=np.array([[0,1,2,3],[4,5,6,7]])
len(M3)

2

In [6]:
[i for i in range(len(M2[0]))]

[0, 1, 2]

In [31]:
m1=M1.sum(axis=1)
print (m1)
print (M1)
m3=M3.sum(axis=1)
m3

[ 2.5  1.3]
[[ 0.5  2. ]
 [ 0.4  0.9]]


array([ 6, 22])

In [8]:
M3[1,:]

array([4, 5, 6, 7])

In [9]:
m1[:,np.newaxis]

array([[ 1.],
       [ 1.]])

In [52]:
np.divide(M1,d)

array([[ 0.0625   ,  0.0625   ],
       [ 0.0125   ,  0.0140625]])

In [53]:
np.divide(d,M1)

array([[ 16.        ,  16.        ],
       [ 80.        ,  71.11111111]])

In [56]:
M1=np.array([[0.5,0.5],[0.1,0.9]])
d=np.array([[2,2],[2,4]])
dd=np.array([[1,4],[4,1]])

print(np.divide(M1,d))
print(np.divide(d,M1))

[[ 0.25   0.25 ]
 [ 0.05   0.225]]
[[  4.           4.        ]
 [ 20.           4.44444444]]


In [26]:
print (dd)
M1=np.array([[0.5,0.5],[0.1,0.9]])
M1*=dd
M1

[[1 4]
 [4 1]]


array([[ 0.5,  2. ],
       [ 0.4,  0.9]])

In [14]:
M1/=m1[:,np.newaxis]
M1

array([[ 0.5  ,  0.125],
       [ 0.025,  0.9  ]])

In [59]:
print(M2)
def normalize(T):
    """
    Given a matrix T, returns another one, T0, with rows that add to 1
    """
    T0=np.array(T)
    s=T0.sum(axis=1)
    T0/=s[:,np.newaxis]
    return T0


normalize(M2)

[[ 0.71353678  0.81560565  0.59779976]
 [ 0.21322577  0.02264318  0.95387865]
 [ 0.02565694  0.51688337  0.30994962]]


array([[ 0.3354754 ,  0.38346395,  0.28106065],
       [ 0.17921933,  0.01903192,  0.80174875],
       [ 0.03009647,  0.60632197,  0.36358156]])

In [60]:
print(M2)

def normalize2(T):
    T0=np.array(T)
    s=T0.sum(axis=1)
    return np.divide(T0,s[:,np.newaxis])

normalize2(M2)

[[ 0.71353678  0.81560565  0.59779976]
 [ 0.21322577  0.02264318  0.95387865]
 [ 0.02565694  0.51688337  0.30994962]]


array([[ 0.3354754 ,  0.38346395,  0.28106065],
       [ 0.17921933,  0.01903192,  0.80174875],
       [ 0.03009647,  0.60632197,  0.36358156]])

In [64]:
def stationary_sol(T):
    """
    Given a random matrix T, returns a stationary sol a, s.t. aT=a
    """
    T0=normalize(T)
    eig=np.linalg.eig(T0)
    for i in range(len(eig)):
        if eig[0][i]==1:
            return eig[1][i]
    return "no eigenvalue 1"


print(stationary_sol(M2))


stationary_sol(M1)

[-0.57735027 -0.97498294  0.18460639]


array([ 0.19611614, -0.70710678])

In [63]:
eig=np.linalg.eig(M1)
eig


eig[0][1]

1.0