# Realization

In [1]:
import numpy as np
import random as r

### Cummulative distribution from distribution

Turns a given distribution 
$$ p = (p_i)_{i=0,...,n-1} $$
into a cummulative distribution
$$ c = (\sum_{k=0}^{i}p_k)_{i=0,...,n-1} $$


In [2]:
def cum_distribution(distribution):
    cum_value = 0
    c_distribution = np.zeros(len(distribution))
    for i in range(0, len(distribution)):
        cum_value += distribution[i]
        c_distribution[i] = cum_value
    return c_distribution

Testing

In [3]:
p1 = np.array([.5, .5], float)
p2 = np.array([.1,.2,.3,.4], float)
c1 = cum_distribution(p2)
c1

array([ 0.1,  0.3,  0.6,  1. ])

### State from [0,1]-Distribution 

In [4]:
def find_state(r_number, cum_distribution):
    not_found = True
    #Cast integer
    id = 0

    while(not_found):
        if r_number < cum_distribution[id]:
            #not_found = False
            return id
        else:
            id = id + 1
        

Testing

In [5]:
p2 = np.array([.1,.3,.6,1], float)
find_state(0.65, p2)

3

### Draw realization of given probability

Given a probability distribution: 

$$ p = (p_i)_{i=0,...,n-1} $$

where the i-th entry is the probability of the i-th state. 

The function chooses a state according to the distribution

In [6]:
def state_from_distribution(distribution):
    #test if distribution is distribution
    #row_stochastic(distribution)
    cumm_distribution = cum_distribution(distribution)
    a = find_state(r.random(), cumm_distribution)
    return a

Testing

In [7]:
r.random()
p1 = np.array([.5, .5], float)
p2 = np.array([.1,.2,.3,.4], float)
print(state_from_distribution(p2))

1


### Draw Trajectory from given start + transition matrix

Given an initial distribution

$$ p_0 = (p_i)_{i=0,...,n-1} $$

and n x n transition matrix T

the function draws a trajectory of L states using the algorithm:

* Initialization: 
    $p_{new} = p_0$, i.e. distribution is chosen to be the inital distribution

* Algorithm:
    1. Use distribution to chose state $i_{random}$
    2. New distribution: $p_{new} = i_{random}$-th row of T


In [8]:
def trajectory(p0, T, L):
    traj = np.zeros(L, dtype=int)
    traj[0] = state_from_distribution(p0)
    
    for i in range(1, L):
        p_new = T[traj[i-1]]
        print("p_new", p_new)
        traj[i] = state_from_distribution(p_new)
        
    print("trajectory", traj)    
    return traj

Testing

In [9]:
p1 = np.array([0.1, 0.9], float)
T = np.array([[0.9, 0.1], [0.5, 0.5]], float)
L = 10
trajectory(p1,T, L)

p_new [ 0.5  0.5]
p_new [ 0.9  0.1]
p_new [ 0.9  0.1]
p_new [ 0.9  0.1]
p_new [ 0.9  0.1]
p_new [ 0.9  0.1]
p_new [ 0.9  0.1]
p_new [ 0.5  0.5]
p_new [ 0.9  0.1]
trajectory [1 0 0 0 0 0 0 1 0 1]


array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

### Ensemble evolution

Determining the probabilility to find the chain at state i at time i given a transition matrix T:

$$p_{t,i} = \sum_{j=1}^{n} p_{t-1,j}T_{1j}$$, i.e.

$$\textbf{p}_t^T = \textbf{p}_{t-1}^{T} \textbf{T}$$ and thus

$$\textbf{p}_k^T = \textbf{p}_{0}^{T} \textbf{T}^k$$

In [10]:
T.dot(p1)

array([ 0.18,  0.5 ])