In [139]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as spy
from scipy import linalg
import pylab as pylab
from pyemma import msm
import matplotlib as mpl

In [4]:
r"""
This module generates trajectories of a simple two dimensional toy model for testing purposes.
"""

import numpy as np

__all__ = ['generate_test_data']

def _gradient(x, y):
    return (x * x - 1.0) * 4.0 * x + 0.5, (4.0 * y * y - 7.0) * y

def _bd(x0, y0, length, dt=0.005):
    coeff_A = dt
    coeff_B = np.sqrt(2.0 * dt)
    x = [x0]
    y = [y0]
    for _i in range(1, length):
        dx, dy = _gradient(x[-1], y[-1])
        x.append(x[-1] - coeff_A * dx + coeff_B * np.random.normal())
        y.append(y[-1] - coeff_A * dy + coeff_B * np.random.normal())
    return np.array([[_x, _y] for _x, _y in zip(x, y)], dtype=np.float64)

def generate_test_data(traj_length=20000, num_trajs=5):
    r"""
    This functions handles the test data generation via Brownian dynamics simulations with
    randomized starting configurations.
    Parameters
    ----------
    traj_length : int, optional, default=20000
        Length of a single trajectory.
    num_trajs : int, optional, default=5
        Number of independent trajectories.
    Returns
    -------
    trajs : list of numpy.ndarray(shape=(traj_length, 2), dtype=numpy.float64) objects
        Time series of configurations of the toy model.
    """
    trajs = []
    for _i in range(num_trajs):
        trajs.append(_bd(3.0 * np.random.rand() - 1.5, 3.0 * np.random.rand() - 1.5, traj_length))
    return trajs

In [5]:
"""
TIMESCALES
"""

def stat(T):
    w, v = np.linalg.eig(T.T)
    
    j_stat =np.argmin(abs(w-1.0))
    p_stat=v[:,j_stat].real
    p_stat /= p_stat.sum()
    return p_stat

def implied_timescales(T_lag,lag):
    """
    Calculates timescale_i(k*lag)=
    
    INPUT:
        - T = A markov transition matrix at a lagtime lag.
        - lag = reference lagtime we are considering.
    """
    
    eig_val, eig_vec=np.linalg.eig(T_lag)
    eig_val = np.absolute(eig_val)
    eig_val = np.sort(eig_val)
    if eig_val[0] == 0:
        eig_val[0] = eig_val[1]
    L=[]
    for i in range(len(eig_val)):
        """if (eig_val[i]==0):
            eig_val[i] = 0.001"""
        ti = -(lag)/(np.log(eig_val[i]))
        """if len(L) == 0:
            L.append(ti)
        else:
            if ti < 0:
                L.append(L[i-1])
            elif ti > 10 * L[i-1]:
                L.append(L[i-1])
            else:
                L.append(ti)"""
        L.append(ti)
    return(L)

def plot_timescales(T,LAG):
    """
    Functio
    
    INPUT:
        - T = A list of markov transition matrices such that T[i] = T(lag), transition matrix at lag time lag.
        - LAG = A list of the lagtimes in which we plot the timescales
    """
    
    if len(T)==len(LAG):
        k=len(LAG)
    else:
        return "Input dimensions dont match"
    
    kk=len(implied_timescales(T[0],LAG[0])) 
    timescale_trajs=[]
    for i in range(kk):
        timescale_trajs.append([])
        
    for l in range(k):
        t_lag=implied_timescales(T[l],LAG[l]) #timescales at lag l
        
        for j in range(len(t_lag)):
            if t_lag[j]<1000:
                (timescale_trajs[j]).append(t_lag[j])
            else:
                """(timescale_trajs[j]).append(timescale_trajs[j][-1])"""
                (timescale_trajs[j]).append(t_lag[j])
    
    #plot slower n_timescales
    """if n_timescales < len(timescale_trajs):
        n = n_timescales
    else:
        n = len(timescale_trajs)"""
    for i in range(len(timescale_trajs)-1):
        if len(LAG) == len(timescale_trajs[i]):
            plt.plot(LAG,timescale_trajs[i],'o',linestyle='-')
        else:
            next
    plt.xlabel('Lag time')
    plt.xscale('log')
    plt.yscale('log')
    plt.ylabel('Implied timescale')
    plt.tight_layout()
    plt.show() 

In [225]:
"""
K-MEANS
"""

import os
import numpy as np

# kmeans clustering algorithm
# data = set of data points
# k = number of clusters
# c = initial list of centroids (if provided)
#
def kmeans(data, k, c):
    centroids = []

    centroids = randomize_centroids(data, centroids, k)  

    old_centroids = [[] for i in range(k)] 

    iterations = 0
    while not (has_converged(centroids, old_centroids, iterations)):
        iterations += 1

        clusters = [[] for i in range(k)]

        # assign data points to clusters
        clusters = euclidean_dist(data, centroids, clusters)

        # recalculate centroids
        index = 0
        for cluster in clusters:
            old_centroids[index] = centroids[index]
            centroids[index] = np.mean(cluster, axis=0).tolist()
            index += 1
    print("The total number of data instances is: " + str(len(data)))
    print("The total number of iterations necessary is: " + str(iterations))
    print("The means of each cluster are: " + str(centroids))
    print("The clusters are as follows:")
    for cluster in clusters:
        print("Cluster with a size of " + str(len(cluster)) + " starts here:")
        print(np.array(cluster).tolist())
        print("Cluster ends here.")

    return

# Calculates euclidean distance between
# a data point and all the available cluster
# centroids.      
def euclidean_dist(data, centroids, clusters):
    for instance in data:  
        # Find which centroid is the closest
        # to the given data point.
        mu_index = min([(i[0], np.linalg.norm(instance-centroids[i[0]])) \
                            for i in enumerate(centroids)], key=lambda t:t[1])[0]
        try:
            clusters[mu_index].append(instance)
        except KeyError:
            clusters[mu_index] = [instance]

    # If any cluster is empty then assign one point
    # from data set randomly so as to not have empty
    # clusters and 0 means.        
    for cluster in clusters:
        if not cluster:
            cluster.append(data[np.random.randint(0, len(data), size=1)].flatten().tolist())

    return clusters


# randomize initial centroids
def randomize_centroids(data, centroids, k):
    for cluster in range(0, k):
        centroids.append(data[np.random.randint(0, len(data), size=1)].flatten().tolist())
    return centroids


# check if clusters have converged    
def has_converged(centroids, old_centroids, iterations):
    MAX_ITERATIONS = 1000
    if iterations > MAX_ITERATIONS:
        return True
    return old_centroids == centroids

def kmeans2(data, k, c):
    centroids = []

    centroids = randomize_centroids(data, centroids, k)  

    old_centroids = [[] for i in range(k)] 

    iterations = 0
    while not (has_converged(centroids, old_centroids, iterations)):
        iterations += 1

        clusters = [[] for i in range(k)]

        # assign data points to clusters
        clusters = euclidean_dist(data, centroids, clusters)

        # recalculate centroids
        index = 0
        for cluster in clusters:
            old_centroids[index] = centroids[index]
            centroids[index] = np.mean(cluster, axis=0).tolist()
            index += 1
    return centroids,clusters

def cloust_list(L, clus_0, a_0, w):
    for i in range(len (clus_0)): 
        for k in range(len (a_0)):
            if  all(a_0[k]==clus_0[i]):
                L[k]=w
    return L

def Clustering(traj,nclus):
    centers, clus = kmeans2(traj, nclus, 5)
    L=[0 for i in range(len(traj))]
    for  b in range(nclus):
        cloust_list(L, clus[b],traj,b)
    return L, centers

In [8]:
"""
COUNTMATRIX
"""

def sliding_window(traj,lag=1):
    """
    Get the count matrix out of the trajectory from clusters.
    
    INPUT:
        traj = A list. A sucesion of states.
        lag = Lagtime we are considering.
        
    OUTPUT:
        A count matrix.
    """
    
    dim = max(traj)+1
    C=np.zeros([dim,dim])
    for i in range(len(traj)-lag):
        C[traj[i],traj[i+lag]] +=1
        
    return C

In [9]:
"""
KOSARAJU
"""

def stat(T):
    w, v = np.linalg.eig(T.T)
    
    j_stat =np.argmin(abs(w-1.0))
    p_stat=v[:,j_stat].real
    p_stat /= p_stat.sum()
    return p_stat

def obtain_active_set(T):
    """
    Function for other parts of the project. It gets the biggest connected component of the matrix 
    that we are given.
    
    INPUT:
        - T = The probability transition matrix of the markov model.
    
    OUTPUT:
        - C = A square matrix. The biggest connected component of the matrix.
        - L = A list of vertices. The states of T that correspond to the biggest component.
    
    """
    
    b=0
    j=0
    components=kosarajus_algo2(T)
    for i in components:
        a=len(components[i])
        if a>b:
            b=a
            j=i
    L=list(components[j])
    L=np.sort(L)
    C=np.array([T[i,:] for i in L])
    C=np.array([C[:,i] for i in L])
    C=np.transpose(C)
    return (C,L)

def Assign2(u,root,LIST,components,M):
    """
    Recursive subfunction for kosarajus
    Strong components are to be represented by appointing a separate root vertex for each component,
    and assigning to each vertex the root vertex of its component.
    
    INPUT:
        
        - u = An integer, which represents a vertex (in our numeration) that has to be
        assigned to some component.
        - root = An integer, which represents a component.
        
        - LIST = A list of vertices that are not yet introduced in the dictionary.
        
        - components = A dictionary containing the vertices (numerated from 0 to n-1), 
        each vertex associated to the root representing its component.
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
    
        - It just changes the dictionary components, assigning to each vertex its root.
    
    """
    
    in_=[i for i in M[:,u]]
    
    if u in LIST:
        
        if not root in components:
            components[root]=[u]
        elif root in components:
            components[root].append(u)
        LIST.remove(u)
            
        for i in range(len(in_)):
            if not(in_[i]==0):
                Assign2(i,root,LIST,components,M)
    return

def Visit(u,Visited,L,M):
    """
    Recursive subfunction for kosarajus
    
    INPUT:
        
        - u = An integer, which represents a vertex (in our numeration).
        - Visited = A list of the vertices already visited.
        - L = an ordered list of graph vertices, that will grow to contain each vertex once.
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
        
        - It just adds in order vertices to the list L.
    
    """
    out=M[u,:]
    if not(u in Visited):
        Visited.append(u)
        for i in range(len(out)):
            if not(out[i]==0):
                Visit(i,Visited,L,M)
        L.insert(0,u) 
    return

def kosarajus_algo2(M):
    """
    Returns a dictionary containing the vertices and their inclusion in strong components.
    Strong components are to be represented by appointing a separate root vertex for each component,
    and assigning to each root the list of vertices inside that component.
    If the graph is represented as an adjacency matrix, the algorithm requires Ο(V^2) time.
    
    INPUT:
    
        - M = A transition matrix (which is the adjacency matrix of a graph).
    
    OUTPUT:
    
        - components = A dictionary containing the components (numerated from 0 to ..), 
        each root associated to a list of vertices that are part of that component.
    
    """
    
    Visited=[]
    L=[]
    
    components={}
    
    Vertices= [i for i in range(len(M[:,1]))]
    LIST=list(Vertices)
    
    for i in Vertices:
        Visit(i,Visited,L,M)
    for u in L:
        Assign2(u,u,LIST,components,M)
    return components  

In [10]:
"""
REVERSIBLE ESTIMATOR
"""

def normalize(M):
    """
    Subfunction for T. It normalizes the matrix given as input.
    
    INPUT:
        - M = A matrix M.
        
    OUTPUT:
        - M0 = The matrix M normalized, with rows that add to 1.     
    """
    
    M0=np.array(M)
    if M0.ndim == 1:
        s= M0.sum()
        return np.divide(M0,s)
        
    elif M0.ndim == 2:
        s=M0.sum(axis=1)
        return np.divide(M0,s[:,np.newaxis])
    else:
        return "Normalize. Wrong input"

def T_non_reversible(C):
    """
    Function to get the transition matrix from the count matrix. It simply normalizes the count matrix.
    Is easy, and useful for very large amount of data.
    
    INPUT:
        - C = Count matrix.
    
    OUTPUT:
        - P = The probability transition matrix of the markov model.
    """
    
    return normalize(C)

def T_reversible(C,max_iterations=100,error=0.1):
    """
    Function to get the transition matrix from the count matrix. It gives a matrix that is reversible.
    That is, the markov model obtained is reversible (it satisfies the detailed balance equations).
    Detailed balance implies that, around any closed cycle of states, there is no net flow of probability. 
    For example, it implies that, for all a, b and c,
    T( a , b ) T( b , c ) T( c , a ) = T( a , c ) T( c , b ) T( b , a ).
    
    INPUT:
        - C = Count matrix constructed with lag tau.
        - max_iterations = maximum number of iterations we allow.
        - error = error that we consider to understand that the iteration has converged.
        
    OUTPUT:
        - P = The probability transition matrix of the markov model.
    """
    
    C_i = C.sum(axis=1) #array of the sums of the rows of C
    C_j = C.sum(axis=0) #array of the sums of the columns of C
    
    P = T_non_reversible(C)
    P = (obtain_active_set(P))[0]
    pi = stat(P)
    
    P=np.multiply(pi,P)
    X_0= P #initial state
    
    it=0
    Er=0.2 #TO BE CHANGED
    
    while (Er > error) and (it< max_iterations):
        Xi_0= X_0.sum(axis=1) #array of the sums of the rows of X_0
        Xj_0= X_0.sum(axis=0) #array of the sums of the rows of X_0
        
        
        X_1= C + np.matrix.transpose(C)
        if not(len(C_i)==len(Xi_0)):
            return X_0
        I = np.divide((C_i),(Xi_0))
        if not(len(C_j)==len(Xj_0)):
            return X_0
        II = np.divide((C_j),(Xj_0))
        denominador = I + II
        X_1=np.divide(X_1,denominador)
        
        X_0 = X_1
        it+=1
        
    P = normalize(X_1)
    return P

In [171]:
def hitting_time_ij(T,i,j,steps):
    """
    Calculates the hitting time between states i, j from the markov transition matrix.
    Since p_ij is the probability of going to state j given that we are in state 
    i, the product π_i * p_ij is the long run proportion of transitions that go from state
    i to state j.
    
    INPUT:
        - T = A markov transiton matrix.
        - i = Some state from which we start.
        - j = Some state where we wanna arrive.
        - steps = An integer. Max number of steps we want to consider.
        
    OUTPUT:
        - A picture showing how hitting probability between i and j changes with time.
        - Limiting probability of going from state i to state j.

    """
    
    A=T.copy()
    
    hit_idx = (i,j)

    # Make the final state an absorbing condition
    A[hit_idx[1],:] = 0
    A[hit_idx[1],hit_idx[1]] = 1

    # Make a proper Markov matrix by row normalizing
    A = (A.T/A.sum(axis=1)).T
    
    B = A.copy()
    Z = []
    for n in range(steps):
        Z.append( B[hit_idx] )
        B = np.dot(B,A)
    
    plt.plot(Z)
    plt.xlabel("steps")
    plt.ylabel("hit probability")
    plt.show()

In [ ]:
"""
MEAN FIRST PASSAGE TIMES
"""


def forward_commitors(T,A,B):
    """
    Formally defined as the probability to hit set B rather than A
    
    INPUT:
        - T = A markov transition matrix
        - A = A subset of states.
        - B = A subset of states.
        
    OUTPUT:
    """

        
    n = len(T)
    
    q=np.zeros(n)
    q[B] = np.ones(len(B))
    
    B_ = [i for i in range(n) if i not in B]
    AB_ = [i for i in B_ if i not in A]
    
    
    a = np.copy(T)
    a = a[:,AB_]
    a = a[AB_,:]
    
    I=np.identity(len(a))
    a=a-I
    
    b = np.copy(T)
    b = b[:,B]
    b = b[AB_,:]

    b=b.sum(axis=1)
    b= -1*b 
    
    if not(len(a)==0 or len(b)==0):
        Q = (np.linalg.lstsq(a,b))[0]
        q[AB_] = Q
    
    return q        

def probability_current(T,A,B):
    """
    ¡¡NOT OPTIMIZED!!
    
    The probability current gives the averege number of reactive trajectories
    (those going from A to B, without entering A before reaching B) that transition
    from i to j per time unit.
    
    """
    
    n = len(T)
    
    F = np.copy(T)
    
    q = forward_commitors(T,A,B)   
    q_ = forward_commitors(T,B,A)
    
    pi=stat(T)
    
    for i in range(n):
        for j in range(n):
            if j==i:
                F[i,j]=0
            else:
                F[i,j] = (pi[i])*(q_[i])*(T[i,j])*(q[j])
    
    return F

def average_current(T,A,B):
    """
    ¡¡NOT OPTIMIZED!!
    
    Average total number of trajectories going from A to B per time unit.
    
    INPUT:
        - T = A markov transition matrix.
        - A = A subset of indices.
        - B = A subset of indices.
    
    """
    
    f_AB = probability_current(T,A,B)
        
    n=len(f_AB)
    F_AB = np.zeros([n,n])
    
    for i in A:
        for j in B:
            F_AB[i,j] = f_AB[i,j]
    F_AB=F_AB.sum(axis=1)
    F_AB=F_AB.sum(axis=0)
    
    return F_AB

def transition_rates(T,A,B):
    """
    ¡¡NOT OPTIMIZED!!
    
    The forward and backward commitor are sufficient to calculate transition rates between 
    the sets A and B
    
    """
    
    F_AB = average_current(T,A,B)
    pi = stat(T)
    q = forward_commitors(T,A,B)
    
    sum=0
    
    for j in B:
        sum= sum + (pi[j])*(q[j])
        
    return (F_AB/sum)

def mean_first_passage_times(T,A,B):
    """
    
    """
    
    t= transition_rates(T,A,B)
    return 1/t

----------------------------------------------------------

In [226]:
trajs = generate_test_data(10000, 5)
traj0 = trajs[0]
traj0[[i for i in range(20)],:]

array([[-0.84880275, -0.54056033],
       [-1.01762825, -0.4775157 ],
       [-0.98980154, -0.18141352],
       [-0.92777929, -0.30822589],
       [-0.95261507, -0.27305554],
       [-0.85960049, -0.18332458],
       [-0.90954901, -0.09218517],
       [-0.94128941, -0.05476683],
       [-0.97196738,  0.02513561],
       [-1.11352097,  0.11810121],
       [-1.0545318 ,  0.0446749 ],
       [-1.11570848,  0.18875362],
       [-0.99446292,  0.19935813],
       [-1.01179418,  0.12654102],
       [-0.98710066,  0.18483019],
       [-0.99701033,  0.17275449],
       [-0.96305458,  0.03393238],
       [-0.92246786,  0.05967699],
       [-1.03527127, -0.09066782],
       [-1.05749059,  0.03060416]])

In [227]:
LAG=[1, 2, 5, 10, 20, 50, 100, 200, 500, 1000]
n_centers = 100

L,centers = Clustering(traj0,n_centers)
centers = np.array(centers)

In [228]:
Ts = []
for i in range(len(LAG)):
    C_lag = sliding_window(L,LAG[i])
    #print(C_lag)
    T_lag = T_reversible(C_lag)
    #print(np.sort(np.linalg.eig(T_lag)[0]))
    Ts.append(T_lag)
plot_timescales(Ts,LAG)

In [229]:
chosen_lag = 13
C_lag = sliding_window(L,chosen_lag)
T_lag = T_reversible(C_lag)
T=T_lag

In [230]:
eig_val, eig_vec = np.linalg.eig(T)
plt.plot(np.absolute(eig_val),'o')
plt.show()

In [231]:
n_pcca_states = 3
pcca=msm.PCCA(T,n_pcca_states)
metastable_assignments = pcca.metastable_assignment
metastable_assignments

array([1, 2, 0, 1, 1, 2, 1, 0, 2, 0, 1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2,
       2, 2, 2, 2, 0, 1, 0, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 1, 2, 1, 2,
       2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 0, 2, 0, 2, 2, 1, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 0, 1, 2, 0, 2, 1, 2, 1, 0, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 1], dtype=int64)

In [232]:
metastable_sets=pcca.metastable_sets
metastable_sets

[array([ 2,  7,  9, 27, 29, 38, 56, 58, 66, 81, 84, 89], dtype=int64),
 array([ 0,  3,  4,  6, 10, 14, 15, 17, 19, 21, 28, 31, 41, 42, 44, 47, 50,
        51, 54, 55, 61, 63, 69, 72, 73, 76, 79, 80, 82, 86, 88, 92, 99], dtype=int64),
 array([ 1,  5,  8, 11, 12, 13, 16, 18, 20, 22, 23, 24, 25, 26, 30, 32, 33,
        34, 35, 36, 37, 39, 40, 43, 45, 46, 48, 49, 52, 53, 57, 59, 60, 62,
        64, 65, 67, 68, 70, 71, 74, 75, 77, 78, 83, 85, 87, 90, 91, 93, 94,
        95, 96, 97, 98], dtype=int64)]

PLOTS

First, plot the trajectories and the centers that the k-means algorithm produces. Each center
represents a cluster.

In [234]:
def format_square(ax):
    ax.set_xlim(-2, 2)
    ax.set_ylim(-2, 2)
    ax.set_xticks([-2, -1, 0, 1, 2])
    ax.set_yticks([-2, -1, 0, 1, 2])
    ax.set_xlabel(r"$x$ / a.u.")
    ax.set_ylabel(r"$y$ / a.u.")
    ax.set_aspect('equal')

fig, ax = plt.subplots(figsize=(5, 5))
for i in range(len(trajs)):
    ax.scatter(trajs[i][::50, 0], trajs[i][::50, 1], c='grey', s=20)
ax.scatter(centers[:, 0], centers[:, 1], c='red', s=50)
format_square(ax)
fig.tight_layout()
plt.show()

Now, looking at the centers, plot the stationary distribution at each center(state). That is, the long term probability of being in that state.

In [235]:
fig, ax = plt.subplots(figsize=(6.5, 5))
im = ax.scatter(centers[:, 0], centers[:, 1], c=stat(T), s=200, cmap=mpl.cm.viridis)
cbar = fig.colorbar(im, ax=ax)
cbar.set_label(r"$\pi(x,y)$", fontsize=20)
format_square(ax)
fig.tight_layout()
plt.show()

Plot of the eigenvectors

In [236]:
n_eig_vec = 5
eig_vec = np.linalg.eig(T)[1]
eig_vec = np.sort(eig_vec)
eig_vec = eig_vec[:,[-(i+1) for i in range(n_eig_vec)]]

fig, axes = plt.subplots(1, 4, figsize=(12, 3.5))
for i, ax in enumerate(axes.flat):
    ax.scatter(centers[:, 0], centers[:, 1], s=80, c=eig_vec[:, i+1], cmap=mpl.cm.viridis)
    format_square(ax)
fig.tight_layout()
plt.show()

Here we plot the different metastable states that pcca has given:

In [237]:
fig, ax = plt.subplots(figsize=(6.5, 5))
im = ax.scatter(centers[:, 0], centers[:, 1], c=metastable_assignments, s=200, cmap=mpl.cm.viridis)
cbar = fig.colorbar(im, ax=ax)
cbar.set_ticks(np.arange(n_pcca_states))
cbar.set_label(r"metastable state", fontsize=20)
format_square(ax)
fig.tight_layout()
plt.show()

Plot the stationary distribution at each metastable state. That is, the long term probability of
being in that state.

In [238]:
pi = stat(T)
pi_states = np.array([pi[s].sum() for s in metastable_sets])
pi_vec = pi[metastable_assignments]

fig, ax = plt.subplots(figsize=(6.5, 5))
im = ax.scatter(centers[:,0], centers[:,1], c=pi_vec, s=200, cmap=mpl.cm.viridis)
cbar = fig.colorbar(im, ax=ax)
cbar.set_label(r"$\pi($metastable state$)$", fontsize=20)
format_square(ax)
fig.tight_layout()
print (pi_states)
plt.show()

[ 0.08658939  0.35447977  0.55893083]


Now we compute a graph with the transitions between states. The size of a state represents
the time that is spent in each state. The size of the arrows represent the probability to 
go from one state to the other (or the number of steps that in media takes to go from one to the other).

In [242]:
mfpt = np.zeros(shape=(n_pcca_states, n_pcca_states))
for i, s1 in enumerate(metastable_sets):
    for j, s2 in enumerate(metastable_sets):
        if s1 is s2: continue
        mfpt[i, j] = mean_first_passage_times(T,s1, s2)

arrow_weights = mfpt.copy()
nz = mfpt.nonzero()
arrow_weights[nz] = 1.0 / arrow_weights[nz]

fig, pos = pyemma.plots.plot_network(
    arrow_weights, xpos=[2*i for i in range(n_pcca_states)], state_sizes=pi_states,
    arrow_labels=mfpt, arrow_label_format="%.0f", arrow_scale=2.0)
fig.tight_layout()
plt.show()

C:\Users\PabloAgustin\Miniconda3\lib\site-packages\ipykernel\__main__.py:123: RuntimeWarning: divide by zero encountered in double_scalars
